# Generated by Django 5.1.7 on 2025-03-23 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('CNPJ', models.CharField(max_length=14)),
                ('telefone', models.CharField(max_length=15)),
                ('url_image', models.ImageField(blank=True, default='salao/default-salon.jpeg', null=True, upload_to='salao/')),
            ],
        ),
    ]
