# Generated by Django 5.1.7 on 2025-03-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salao',
            name='url_image',
            field=models.ImageField(blank=True, default='media/default-salon.jpeg', null=True, upload_to='media/'),
        ),
    ]
