# Generated by Django 5.1.7 on 2025-03-24 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0001_initial'),
        ('servico', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='servico_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='servico.servico'),
            preserve_default=False,
        ),
    ]
