# Generated by Django 5.1.7 on 2025-03-24 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salao', '0002_alter_salao_url_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_image', models.ImageField(blank=True, default='produto/default-product.png', null=True, upload_to='produto/')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField()),
                ('quantidade_estoque', models.IntegerField()),
                ('salao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salao.salao')),
            ],
        ),
    ]
